# Nixpacks configuration for Railway deployment
[phases.setup]
nixPkgs = ["nodejs", "npm", "ffmpeg"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
